format:
	@gofmt -l -s -w . && go mod tidy

run_nethttp:
	@go run ./net_http_package.go

run_gin:
	@go run ./gin_framework.go

run_echo:
	@go run ./echo_framework.go

run_fiber:
	@go run ./fiber_framework.go

run_fasthttp:
	@go run ./fasthttp_framework.go
